### ISSUE TITLE
关于混淆矩阵

### ISSUE THREAD

**Issue by zangtuo** [Nanasaki-Ai/FR-AGCN#1]
你好，我想问一下论文中的混淆矩阵是怎么画的，还望赐教

**Comment by Nanasaki-Ai** [comment]
非常感谢对FR-AGCN这份工作的关注！

关于你的问题，我已上传相关代码，请参考main中的混淆矩阵可视化文件：
Confusion_Matrix_Visualization.py
注意修改地址。

**Comment by zangtuo** [comment]
> 非常感谢对FR-AGCN这份工作的关注！
> 
> 关于你的问题，我已经上传相关代码，请参考main中的混合矩阵可视化文件： Confusion_Matrix_Visualization.py 注意修改地址。

非常感谢！祝科研顺利！
